### PR TITLE
fix: work with 4.8.3

### LINKED ISSUE #482: TypeScript 4.8 complains `*.d.ts`
**Describe the bug**
Once we bump our `typescript` version from 4.7.4 to 4.8.2, `@oclif/core` start failing to compile: https://github.com/autifyhq/autify-cli/pull/84

```
    > @autifyhq/autify-cli@0.8.0-beta.0 build
    > shx rm -rf dist && tsc -b

    node_modules/@oclif/core/lib/command.d.ts(100,35): error TS2344: Type 'F' 
    does not satisfy the constraint 'FlagOutput'.
    node_modules/@oclif/core/lib/command.d.ts(100,92): error TS2344: Type 'F' 
    does not satisfy the constraint 'OutputFlags<any>'.
    node_modules/@oclif/core/lib/parser/index.d.ts(9,35): error TS2344: Type 
    'TFlags' does not satisfy the constraint 'FlagOutput'.
    node_modules/@oclif/core/lib/parser/index.d.ts(9,74): error TS2344: Type 
    'TFlags' does not satisfy the constraint 'OutputFlags<any>'.

    Code: 1
```

**To Reproduce**
1. Pull the dependabot branch from https://github.com/autifyhq/autify-cli/pull/84
2. `npm run build`

**Expected behavior**
No failure on `tsc`.

**Screenshots**
N/A

**Environment (please complete the following information):**
`ubuntu-latest` and `macos-latest` of GitHub Actions hosted runners. `@oclif/core` is updated to the latest (1.16.0) https://github.com/autifyhq/autify-cli/pull/85

**Additional context**
Originally this issue was reported by https://github.com/oclif/core/issues/480 but closed by the author. Hence, this one.

### PR DESCRIPTION
**Pull request by mdonnalley**
Update types to work with typescript@4.8.3

Fixes #482 

@W-11757550@

### CODE REVIEW

**Review by RodEsp — APPROVED** [review]
Verified that using `npm link @oclif/core` with this PR's branch on https://github.com/autifyhq/autify-cli/pull/115 works and `npm run build` succeeds.
