### ISSUE TITLE
Errors with 1.16.4 and typescript 4.8.3

### ISSUE THREAD

**Issue by critesjosh** [oclif/core#501]
**Describe the bug**
I am seeing these compilation errors when trying to run a command after updateing oclif/core to 1.16.4 and typescript to 4.8.3

```
src/base.ts:37:23 - error TS2417: Class static side 'typeof BaseCommand' incorrectly extends base class static side 'typeof Command'.
  Types of property 'flags' are incompatible.
    Type '{ logSdk: IBooleanFlag<boolean>; }' is not assignable to type 'FlagInput<{ [flag: string]: any; }>'.
      Property 'logSdk' is incompatible with index signature.
        Type 'IBooleanFlag<boolean>' is not assignable to type 'CompletableFlag<any>'.
          Type 'IBooleanFlag<boolean>' is not assignable to type 'BooleanFlag<any>'.
            Type 'IBooleanFlag<boolean>' is not assignable to type '{ parse: FlagParser<any, boolean, any>; }'.
              The types returned by 'parse(...)' are incompatible between these types.
                Type 'boolean' is not assignable to type 'Promise<any>'.
```

**To Reproduce**
1. clone this repo, https://github.com/critesjosh/azteccli
2. update package versions mentioned above
3. run a command

**Expected behavior**
I expect it to compile.

**Environment (please complete the following information):**
 - MacOS Monterey
 - Shell/terminal & version, GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)

**Comment by critesjosh** [comment]
i fixed this by adding `as any` to the flag.

```
  static flags = {
    logSdk: Flags.logSdk as any,
  };
```
