### ISSUE TITLE
The code from Table's documentation page is incorrect and results in error after migration to 2.x

### ISSUE THREAD

**Issue by Pavek** [oclif/core#369]
The code from Table's documentation page (from [here](https://oclif.io/docs/table)) results in error:

```
async run() {
    CliUx.ux.table(users, {...}, {
      printLine: this.log, // <-- this is incorrect
      ...flags, // parsed flags
    })
  }
```

The error is:

```
TypeError: this.jsonEnabled is not a function
    at Object.log [as printLine] (D:\projects\karamba\git\vcode\packages\cli-client\node_modules\@oclif\core\lib\command.js:80:19)
    at Table.outputTable (D:\projects\karamba\git\vcode\packages\cli-client\node_modules\@oclif\core\lib\cli-ux\styled\table.js:234:21)
    at Table.display (D:\projects\karamba\git\vcode\packages\cli-client\node_modules\@oclif\core\lib\cli-ux\styled\table.js:105:22)
    at Object.table (D:\projects\karamba\git\vcode\packages\cli-client\node_modules\@oclif\core\lib\cli-ux\styled\table.js:279:39)
```

The correct example code is:
```
async run() {
    CliUx.ux.table(users, {...}, {
      printLine: this.log.bind(this), // <--
      ...flags, // parsed flags
    })
  }
```

**Comment by peternhale** [comment]
@Pavek Thank for reporting this issue.
