### ISSUE TITLE
Flag parse context is not a `Command` instance

### ISSUE THREAD

**Issue by forivall** [oclif/core#621]
**Describe the bug**

While [FlagParserContext](https://github.com/oclif/core/blob/cb29ca732928df8e4897e240380c9fa1d632758d/src/interfaces/parser.ts#L180) claims to be a command instance, due to using spread (introduced in https://github.com/oclif/core/commit/cb29ca732928df8e4897e240380c9fa1d632758d ), the prototype is lost, so all methods are inaccessible from flag parsers.

**To Reproduce**
1. Check out https://github.com/forivall/oclif-hello-world/tree/flag-parse-context-invalid (fork of hello world with repro)
2. Yarn, Build
3. run `./bin/run hello sailor --ahoy --from pirates`
	```
	» ./bin/run hello sailor --ahoy --from pirates
    TypeError: Parsing --ahoy 
      context.logToStderr is not a function
    See more help with --help
	```
3. run `./bin/run hello sailor --ahoy --from captain`
	```
	» ./bin/run hello sailor --ahoy --from captain
    TypeError: Parsing --ahoy 
      context.log is not a function
    See more help with --help
	```

**Expected behavior**
With `pirates`, the string `Pirates involved.` should be output, with exit code 1.

With `captain`, should print `Ahoy!` before `hello sailor from captain! (./src/commands/hello/index.ts)`

**Screenshots**
<img width="408" alt="Screenshot 2023-02-10 at 8 22 59 PM" src="https://user-images.githubusercontent.com/760204/218239681-f2ad5c2b-0b34-477b-b51f-6264c36bf7d6.png">

Repro also at https://github.com/forivall/oclif-hello-world/tree/flag-parse-context-invalid

**Environment (please complete the following information):**
 - OS & version: MacOS Ventura 13.1
 - Shell/terminal & version: vscode integrated terminal, zsh 5.9, node v16.17.0

**Additional context**
https://github.com/oclif/core/commit/cb29ca732928df8e4897e240380c9fa1d632758d has also broken the `Flags.version` and `Flags.help` although those are never hit by standard commands since those flags are now handled by the `require('@oclif/core').run()` method.
